config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'welcome/index'

  post 'users/create', to: 'users#create', as: 'create'

  get '/confirmation_email', to: "users#confirmation_email", as: 'confirmation_email'
  get '/unsubscribe', to: "users#unsubscribe", as: 'unsubscribe'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

  has_secure_token :confirmation_token
  has_secure_token :unsubscribe_token

  def validate_email
    self.confirmed = true
    self.confirmation_token = nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    params[:email]
    @user = User.new(email: params[:email])

    # if request.xhr?
      # respond_to do |format|
        if @user.save
          UserMailer.email_confirmation(@user).deliver_now
        end
      # end
    # end
  end

  def confirmation_email
    user = User.find_by_confirmation_token(params[:token])

    if user
      user.validate_email
      user.save
      p '*' * 80
      p 'User confirmed'
    end
  end

  def unsubscribe
    user = User.find_by_unsubscribe_token(params[:token])

    if user
      user.destroy
      p '*' * 80
      p 'User deleted'
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Poopood</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_email_form.html.erb
<div class='container'>
  <div class='row justify-content-center'>
    <div class='col-6'>
      <%= form_with url: create_url, class: 'form-inline needs-validation', novalidate: 'novalidate' do |form| %>
      <div class='input-group input-group-lg col'>
        <%= form.text_field :email, id: :email, class: 'form-control', placeholder: 'Join Our Mailing List' %>
        <div class='invalid-feedback'></div>
        <div class='input-group-append'>
          <button type='submit' class='btn btn-primary'>Submit</button>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 welcome">
      <h1>Welcome#index</h1>
      <p>Find me in app/views/welcome/index.html.erb</p>
      <%= render 'partials/email_form' %>
    </div>
  </div>
</div>